# Site
title: by and for engineers
email: yone.info@gmail.com
description: >
  技術や気になったものを思いつきと気まぐれで書いています
url: "https://yulii.github.io"
author: Ryo Yoneyama (@yulii)
copyright: "2008-2020, yulii"

# Common Variables
author_img_path: "/img/site/yulii.jpg"
cover_img_path: "/img/site/by-and-for-engineers.jpg"

# Config
timezone: "Asia/Tokyo"
permalink: /:title-:year:month:day.html
exclude: ["bin", "vendor", "Gemfile", "Gemfile.lock"]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   []

# Pagination
paginate: 5
paginate_path: /:num/

# Gem
plugins:
  - jekyll-paginate
  - jemoji
